# Generated by Django 4.1.6 on 2023-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
