# Generated by Django 4.1.6 on 2023-02-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_journey_ended_at_alter_movement_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.journey'),
        ),
    ]
