# Generated by Django 4.1.6 on 2023-02-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_movement_journey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='Movement',
            new_name='movement',
        ),
    ]
